### ISSUE TITLE
Project doesn't compile with latest librdkafka-dev on Ubuntu

### ISSUE THREAD

**Issue by hamshif** [bookingcom/perl-Net-Kafka#4]
librdkafka-dev/bionic,now 0.11.3-1build1 amd64 [installed]
➜  perl-Net-Kafka git:(master) ✗ perl Makefile.pl
Can't open perl script "Makefile.pl": No such file or directory
➜  perl-Net-Kafka git:(master) ✗ perl Makefile.PL
WARNING: Installed librdkafka version 0.11.3 is lower than tested 1.0.0 at Makefile.PL line 21.
Compiling Net::Kafka with librdkafka 0.11.3

Generating a Unix-style Makefile
Writing Makefile for Net::Kafka
Writing MYMETA.yml and MYMETA.json

here is the make error

librdkafka-dev/bionic,now 0.11.3-1build1 amd64 [installed]
➜  perl-Net-Kafka git:(master) ✗ perl Makefile.pl
Can't open perl script "Makefile.pl": No such file or directory
➜  perl-Net-Kafka git:(master) ✗ perl Makefile.PL
WARNING: Installed librdkafka version 0.11.3 is lower than tested 1.0.0 at Makefile.PL line 21.
Compiling Net::Kafka with librdkafka 0.11.3

Generating a Unix-style Makefile
Writing Makefile for Net::Kafka
Writing MYMETA.yml and MYMETA.json

**Comment by xsawyerx** [comment]
You don't have a compilation error here.

What you have is:
* An error for using a file that doesn't exist. Perl (and specifically this module) uses `Makefile.PL`. You started with `Makefile.pl` and you got an error for trying to run a file that doesn't exist.
* You then used the right one and you received a warning or debug output that says it's an unfamiliar version of libkafka. This is to tell you that you're using a fairly old version of Kafka on your computer, which means this module can't 100% guarantee everything will work correctly once you use it.
* Everything after that went well and it built the rest of the files necessary for the installation.

For the record, here is how you install this module:

Option 1: (If you have `cpanm`)
* `cpanm Net::Kafka`

Option 2: (If you don't have `cpanm`)
* `cpan Net::Kafka`

Option 3:
* When inside the directory: `cpanm .`

Option 4: (Completely manually)
* `perl Makefile.PL`
* `make`
* `make test`
* `make install`

This is a very similar to other automake programs (most C programs) which go through `./Configure && make && make test && make install`, except the first step (`./Configure`) is replaced with `perl Makefile.PL`.

You should probably use `cpanm` or `cpan` since they provide a much better experience by also tracking all dependencies, fetching them, and installing for you.

If you don't have `cpanm`, you can install it in Ubuntu with the command:

`sudo apt install cpanminus`
